openapi: 3.1.1
info: 
  title: Minha API
  description: Projeto de uma API REST usando ExpressJS e Mongoose.
  version: 0.1.0
servers:
  - url: http://localhost:3000/
    description: Ambiente de desenvolvimento
tags:
  - tarefas
paths:
  /tarefas:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
        500:
          content:
    post:
      requestBody:
        content:
            application/json:
              schema:
                type: object
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
        422:
          content:
            application/json:
              schema:
                type: object
        500:
          content:

  /tarefas/id:
    get:
      parameters:
        -in: path
        name: tarefaId
        type: string
        required: true
      responses:
        200:
    put:

    delete:
components:

