openapi: 3.0.0
info:
  title: Minha API REST
  version: 0.1
servers:
  - url: http://localhost:3000/
tags:
  - name: usuarios
paths:
  /usuarios:
    post:
      tags:
        - usuarios
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - senha
        responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuario"
        422:
          description: Email e Senha são obrigatórios
          content:
            application/json:
              schema:
                properties:
                  msg: "Email e Senha são obrigatórios"
    delete:
      tags:
        - usuarios
      parameters:
        - name: id
          schema:
            type: string
      responses:
        204
  /usuarios/login:
    post:
      tags:
        - usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - usuario
                - senha
              properties:
                usuario:
                  type: string
                senha:
                  type: string
      responses:
        200:
          description: Token gerado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
  /usuarios/renovar:
    post:
      tags:
        - usuarios
      security:
        - JWTAuth: []
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
        401:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
components:
  schemas:
    Usuario:
      properties:
        email:
          type: string
        senha:
          type: string
    Mensagem:
      type: object
      properties:
        msg:
          type: string
  securitySchemes:
    JWTAuth:
      type: apiKey
      in: header
      name: authorization
